# Django imports
from django.conf.urls import url, include

# Local imports
from .views import (
    CourseCreateListAPIView,
    CourseUpdateApiView,
    CourseSectionCreateApiView,
    CourseSectionListAPIView,
    CourseSectionUpdateApiView,
    CourseFileCreateAPIView,
    CourseFileUpdateAPIView,
    CoursesDetailAPIView,
    CourseDetailTabCreateAPIView,
    CourseDetailTabUpdateAPIView,
    CourseDetailTabListCreateApiView,
    CourseDetailTabListUpdateApiView,
    CoursesFullDetailAPIView,
    CategoryCreateApiView,
    CategoryUpdateApiView,
    CategoryCourseCreateListApiView,
    CategoryCourseUpdateApiView,
    )

urlpatterns = [
    url(
        r'^course/$',
        CourseCreateListAPIView.as_view(),
        name='admin_course_create',
    ),
    url(
        r'^course/(?P<pk>[0-9a-z-]+)/$',
        CourseUpdateApiView.as_view(),
        name='course_detail',
    ),
    url(
        r'^course-section-create/$',
        CourseSectionCreateApiView.as_view(),
        name='course_section_create',
    ),
    url(
        r'^course-section-detail/$',
        CourseSectionListAPIView.as_view(),
        name='course_section_list',
    ),
    url(
        r'^course-section/(?P<pk>[0-9a-z-]+)/$',
        CourseSectionUpdateApiView.as_view(),
        name='course_section_update',
    ),
    url(
        r'^course-section-file-create/$',
        CourseFileCreateAPIView.as_view(),
        name='course_section_file_create',
    ),
    url(
        r'^course-section-file/(?P<pk>[0-9a-z-]+)/$',
        CourseFileUpdateAPIView.as_view(),
        name='course_section_file',
    ),
    url(
        r'^all-course-detail/$',
        CoursesDetailAPIView.as_view(),
        name='all_course_detail',
    ),
    url(
        r'^course-detail-tab-create/$',
        CourseDetailTabCreateAPIView.as_view(),
        name='course_detail_tab_create',
    ),
    url(
        r'^course-detail-tab/(?P<pk>[0-9a-z-]+)/$',
        CourseDetailTabUpdateAPIView.as_view(),
        name='course_detail_tab',
    ),
    url(
        r'^course-detail-tab-list-create/$',
        CourseDetailTabListCreateApiView.as_view(),
        name='course_detail_tab_list_create',
    ),
    url(
        r'^course-detail-tab-list/(?P<pk>[0-9a-z-]+)/$',
        CourseDetailTabListUpdateApiView.as_view(),
        name='course_detail_tab_list',
    ),
    url(
        r'^course-detail/$',
        CoursesFullDetailAPIView.as_view(),
        name='all_course_detail',
    ),
    url(
        r'^category/$',
        CategoryCreateApiView.as_view(),
        name='category_create',
    ),
    url(
        r'^category/(?P<pk>[0-9a-z-]+)/$',
        CategoryUpdateApiView.as_view(),
        name='category_detail',
    ),
    url(
        r'^category-course/$',
        CategoryCourseCreateListApiView.as_view(),
        name='category_course',
    ),
    url(
        r'^category-course/(?P<pk>[0-9a-z-]+)/$',
        CategoryCourseUpdateApiView.as_view(),
        name='category_course_detail',
    ),
]